// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_wrXHlO1vUcnK_782F873LBDIdnypj0',
    appId: '1:897385819686:web:a95808a87c6664eb7340e7',
    messagingSenderId: '897385819686',
    projectId: 'legacyendurancesport',
    authDomain: 'legacyendurancesport.firebaseapp.com',
    storageBucket: 'legacyendurancesport.firebasestorage.app',
    measurementId: 'G-HK26J2B2DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATEvfc5k8UDCEw1Iv-SzQ18KykXmmwxIA',
    appId: '1:897385819686:android:e785bd59b655faea7340e7',
    messagingSenderId: '897385819686',
    projectId: 'legacyendurancesport',
    storageBucket: 'legacyendurancesport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI_GcX5NM9kxEEseGgvJw5Pex8aQQEd9Q',
    appId: '1:897385819686:ios:1c8e3a81160d27ee7340e7',
    messagingSenderId: '897385819686',
    projectId: 'legacyendurancesport',
    storageBucket: 'legacyendurancesport.firebasestorage.app',
    iosBundleId: 'com.example.legacyendurancesport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI_GcX5NM9kxEEseGgvJw5Pex8aQQEd9Q',
    appId: '1:897385819686:ios:1c8e3a81160d27ee7340e7',
    messagingSenderId: '897385819686',
    projectId: 'legacyendurancesport',
    storageBucket: 'legacyendurancesport.firebasestorage.app',
    iosBundleId: 'com.example.legacyendurancesport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_wrXHlO1vUcnK_782F873LBDIdnypj0',
    appId: '1:897385819686:web:ebabda78a5325b777340e7',
    messagingSenderId: '897385819686',
    projectId: 'legacyendurancesport',
    authDomain: 'legacyendurancesport.firebaseapp.com',
    storageBucket: 'legacyendurancesport.firebasestorage.app',
    measurementId: 'G-ZJ00GNNWBG',
  );
}
